env: "local"
storage: 
    username: "postgres"
    password: "qwerty"
    host: "localhost"
    port:  "5432"
    database: "postgres"
nats_streaming:
    cluster_id: "test-cluster"
    client_id: "test-client"
http_server:
    address: "localhost:8081"
    timeout: 4s
    idle_timeout: 60s
